version: "3"

services:

  php:
      build:
          context: .
          dockerfile: ./images/phpfpm/Dockerfile
      volumes:
          - './src:/var/www/html'
      depends_on:
          - db

  nginx:
      image: nginx:latest
      ports:
          - '80:80'
          - '443:443'
      volumes:
          - './src:/var/www/html'
          - './images/nginx:/etc/nginx/conf.d'
      depends_on:
        - php


  db:
      image: mysql:5.7
      ports:
          - "3306:3306"
      environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: database
          MYSQL_USER: user
          MYSQL_PASSWORD: password
      volumes:
          - dbdata:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      environment:
          PMA_HOST: db
          PMA_USER: user
          PMA_PASSWORD: password
      ports:
      - 8081:80

  mailhog:
      image: mailhog/mailhog
      ports:
          - "1025"
          - "8025:8025"

#  rabbitmq:
#      image: docker.io/bitnami/rabbitmq:3.9
#      ports:
#          - "15672:15672"
#          - "5672:5672"
#      environment:
#          - RABBITMQ_SECURE_PASSWORD=yes
##          - RABBITMQ_USERNAME=user
##          - RABBITMQ_PASSWORD=bitnami
#      volumes:
#          - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'

#  elasticsearch:
#      image: markoshust/magento-elasticsearch:7.7
#      ports:
#          - "9200:9200"
#          - "9300:9300"
#      environment:
#          - "discovery.type=single-node"

volumes:
  dbdata:
#  rabbitmq_data:
#      driver: local